server:
  port: 7099

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
    

spring:
  application:
    name: customer-client-service

 
 
logging:
  level:
    org.exampledriven.eureka.customer.shared.CustomerServiceFeignClient: FULL
    org.exampledriven.eureka: DEBUG


    